Investor.Web/Pages/Account/Login.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Threading.Tasks;
using Investor.Web.Data.Models;
using Investor.Web.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Investor.Web.Pages.Account
{
    public class Login : PageModel
    {
        private readonly SignInService _signInService;

        public Login(SignInService signInService)
        {
            _signInService = signInService;
        }
        
        [BindProperty] 
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }
        
        [TempData] 
        public string ErrorMessage { get; set; }
        
        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
            
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }
            
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }
        public void OnGet(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            HttpContext.SignOutAsync();
            ReturnUrl = returnUrl;
        }

        public IActionResult OnPost(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            if (ModelState.IsValid)
            {
                switch (_signInService.ValidateAccount(Input.Email, Input.Password))
                {
                    case AccountStatus.Banned:
                        ModelState.AddModelError(string.Empty, "Your account has been banned LOL");
                        return Page();
                    case AccountStatus.Disabled:
                        ModelState.AddModelError(string.Empty, "Your account has been disabled.");
                        return Page();
                    case AccountStatus.Unauthenticated:
                        ModelState.AddModelError(string.Empty, "Invalid credentials.");
                        return Page();
                    case AccountStatus.LockedOut:
                        ModelState.AddModelError(string.Empty, "Account locked.");
                        return Page();
                    case AccountStatus.PendingVerification:
                        ModelState.AddModelError(string.Empty, "Your account is pending verification.");
                        return Page();
                    case AccountStatus.Ok:
                        _signInService.SignIn(Input.Email, Input.RememberMe, HttpContext);
                        return RedirectToPage("Success");
                }
            }
            
            // If we got this far, something failed, redisplay form
            ModelState.AddModelError(string.Empty, "An unexpected error occured.");
            return Page();
        }

        public async Task<IActionResult> OnGetLogout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return LocalRedirect(Url.Content("~/"));
        }
    }
}

Investor.Web/Pages/Account/Logout.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Investor.Web.Pages.Account
{
    public class Logout : PageModel {
        private readonly ILogger<Logout> _logger;

        public Logout(ILogger<Logout> logger) {
            _logger = logger;
        }

        public async Task<IActionResult> OnGet() {
            if (!User.Identity.IsAuthenticated) return Page();
            _logger.LogInformation($"Logging {User.Identity.Name} out.");
            await HttpContext.SignOutAsync();
            //Do a redirect so that the username is cleared from the layout.
            return RedirectToPage();
        }
    }
}

Investor.Web/Pages/Account/Register.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Investor.Web.Data.Data;
using Investor.Web.Data.Models;
using Investor.Web.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Investor.Web.Pages.Account
{
    // Register Class
    public class Register : PageModel
    {
        private readonly InvestorContext _dbContext;
        private readonly ILogger<Register> _logger;
        public Register(InvestorContext dbContext, ILogger<Register> logger)
        {
            _dbContext = dbContext;
            _logger = logger;
        }
        
        [BindProperty] public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        // Class to create Input Model 
        public class InputModel {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.",
                MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            [Required]
            [Display(Name = "First Name")]
            public string FirstName { get; set; }

            [Required]
            [Display(Name = "Last Name")]
            public string LastName { get; set; }

            [Display(Name = "Preferred Name")]
            public string PreferredName { get; set; }

            [Required]
            [Display(Name = "Date Of Birth")]
            [DataType(DataType.Date)]
            public DateTime DateOfBirth { get; set; }
        }
        public void OnGet(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
        }

        public IActionResult OnPost(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");
            if (!ModelState.IsValid) return Page();

            if (AccountService.IsEmailInUse(Input.Email, _dbContext))
            {
                _logger.LogWarning($"An account with {Input.Email} already exist");
                ModelState.AddModelError("All", "Email already in use. ");
                return Page();
            }

            var (passwordHash, passwordSalt) = PasswordHasher.HashPassword(Input.Password);
            var accountToAdd = new Data.Models.Account
            {
                Email = Input.Email,
                PasswordHash = passwordHash,
                PasswordSalt = passwordSalt,
                CreatedAt = DateTime.UtcNow,
                Status = (int) AccountStatus.PendingVerification,
                UserRole = 3
            };
            
            _logger.LogTrace($"Attempting to create account for {accountToAdd.Email}");
            _dbContext.Accounts.Add(accountToAdd);
            _dbContext.SaveChanges();
            _logger.LogInformation($"Created account {accountToAdd.Email}");
            
            var account = _dbContext.Accounts.First(a => a.ID == accountToAdd.ID);
            
            // TODO: populate other fields such as phone and birthday
            var profileToAdd = new Profile
            {
                AccountID = account.ID,
                FirstName = Input.FirstName,
                LastName = Input.LastName,
                PreferredName = Input.PreferredName,
            };
            
            _logger.LogTrace($"Attempting to create profile for Account {account.ID}");
            _dbContext.Profiles.Add(profileToAdd);
            _dbContext.SaveChanges();
            _logger.LogInformation("Created profile.");

            return RedirectToPage("Login");
        }
    }
}

Investor.Web/Pages/Account/Success.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Investor.Web.Pages.Account
{
    public class Success : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

Investor.Web/Pages/Admin/Account/Edit.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Investor.Web.Data.Data;
using Investor.Web.Data.Models;
using Investor.Web.Pages.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Investor.Web.Pages.Admin.Account
{
    public class Edit : PageModel
    {
        private readonly InvestorContext _dbContext;
        
        public Data.Models.Account Account { get; set; }
        public Data.Models.Profile Profile { get; set; }
        
        [BindProperty]
        public InputModel Input { get; set; }

        public Edit(InvestorContext dbContext)
        {
            _dbContext = dbContext;
        }
        
        public class InputModel {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }
            
            [Required]
            [Display(Name = "Account Status")]
            [EnumDataType(typeof(AccountStatus))]
            public AccountStatus Status { get; set; }
            
            [Required]
            [Display(Name = "User Role")]
            [EnumDataType(typeof(UserRoles))]
            public UserRoles UserRole { get; set; }
            
            [Required]
            [Display(Name = "First Name")]
            public string FirstName { get; set; }

            [Required]
            [Display(Name = "Last Name")]
            public string LastName { get; set; }

            [Display(Name = "PreferredName")]
            public string PreferredName { get; set; }
            
            [Display(Name = "Phone Number")]
            [DataType(DataType.PhoneNumber)]
            public string Phone { get; set; }

            [Display(Name = "Date Of Birth")]
            [DataType(DataType.Date)]
            public DateTime? DateOfBirth { get; set; }
        }
        
        public IActionResult OnGet(int id)
        {
            Account = _dbContext.Accounts.FirstOrDefault(f => f.ID == id);
            Profile = _dbContext.Profiles.FirstOrDefault(f => f.AccountID == id);
            if (Account == null || Profile == null) return NotFound();

            Input = new InputModel()
            {
                FirstName = Profile.FirstName,
                LastName = Profile.LastName,
                PreferredName = Profile.PreferredName,
                Phone = Profile.Phone,
                Email = Account.Email,
                UserRole = (UserRoles)Account.UserRole,
                Status = (AccountStatus)Account.Status
            };
            return Page();
        }
        
        public IActionResult OnPostGeneral(int id)
        {
            Account = _dbContext.Accounts.FirstOrDefault(f => f.ID == id);
            Profile = _dbContext.Profiles.FirstOrDefault(f => f.AccountID == id);
            if (Account == null || Profile == null) return NotFound();

            Account.Email = Input.Email;
            Account.Status = (int)Input.Status;
            Account.LastModifiedAt = DateTime.UtcNow;
            Account.UserRole = (int)Input.UserRole;
            
            Profile.Phone = Input.Phone;
            Profile.FirstName = Input.FirstName;
            Profile.LastName = Input.LastName;
            Profile.PreferredName = Input.PreferredName;

            _dbContext.Update(Account);
            _dbContext.Update(Profile);
            _dbContext.SaveChanges();
            
            return RedirectToPage();
        }
    }
}

Investor.Web/Pages/Admin/Account/Index.cshtml.cs
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Investor.Web.Data.Data;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Investor.Web.Pages.Admin.Account
{
    public class Index : PageModel
    {
        private readonly InvestorContext _dbContext;

        public Index(InvestorContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IEnumerable<Data.Models.Account> Accounts;
        
        public void OnGet()
        {
            Accounts = _dbContext.Accounts.ToList();
        }
    }
}

Investor.Web/Pages/Admin/Account/Pending.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Investor.Web.Data.Data;
using Investor.Web.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Investor.Web.Pages.Admin.Account
{
    public class Pending : PageModel
    {
        private readonly InvestorContext _dbContext;
        public IEnumerable<Data.Models.Account> PendingAccounts;

        public Pending(InvestorContext dbContext)
        {
            _dbContext = dbContext;
        }
        
        public void OnGet()
        {
            PendingAccounts = _dbContext.Accounts.Where(p => p.Status == (int) AccountStatus.PendingVerification);
        }

        public IActionResult OnGetUpdateStatus(int id, bool approve)
        {
            var account = _dbContext.Accounts.FirstOrDefault(f => f.ID == id);
            if (account == null) return NotFound();

            account.Status = approve ? (int)AccountStatus.Ok : (int)AccountStatus.Disabled;
            _dbContext.Accounts.Update(account);
            _dbContext.SaveChanges();
            return RedirectToPage();
        }
    }
}

Investor.Web/Pages/Admin/Account/Roles.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Investor.Web.Pages.Admin.Account
{
    public class Roles : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

Investor.Web/Pages/Admin/Account/Edit.cshtml
@page "{id}"
@using Investor.Web.Data.Models
@model Investor.Web.Pages.Admin.Account.Edit

@{
    ViewData["Title"] = "User Edit";
}
<!-- Content Header (Page header) -->
<div class="content-header" xmlns="http://www.w3.org/1999/html">
<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">User Profile (@Model.Profile.PreferredName)</div>
        <!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a asp-page="/Admin/Account/Index">Accounts</a></li>
                <li class="breadcrumb-item active">@Model.Profile.PreferredName</li>
            </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="row">
    <div class="col-md-6">
      <form asp-page-handler="General" asp-route-id="@Model.Account.ID" method="post">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">General Account Information</h3>
          </div>
          <div class="card-body">
            <div class="form-group">
              <label asp-for="Input.Email"></label>
              <input asp-for="Input.Email" class="form-control" />
              <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
              <label asp-for="Input.FirstName"></label>
              <input asp-for="Input.FirstName" class="form-control" />
              <span asp-validation-for="Input.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
              <label asp-for="Input.LastName"></label>
              <input asp-for="Input.LastName" class="form-control" />
              <span asp-validation-for="Input.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
              <label asp-for="Input.PreferredName"></label>
              <input asp-for="Input.PreferredName" class="form-control" />
              <span asp-validation-for="Input.PreferredName" class="text-danger"></span>
              <small id="perferredNameHelp" class="form-text text-muted">Optional</small>
            </div>
            <div class="form-group">
              <label asp-for="Input.Phone"></label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="fas fa-phone"></i></span>
                </div>
                <input asp-for="Input.Phone" type="text" class="form-control" data-inputmask="&quot;mask&quot;: &quot;(999) 999-9999&quot;" data-mask="" im-insert="true">
              </div>
              <small id="phoneHelp" class="form-text text-muted">Optional</small>
            </div>
            <div class="form-group">
              <label asp-for="Input.DateOfBirth"></label>
              <input asp-for="Input.DateOfBirth" class="form-control" />
              <span asp-validation-for="Input.DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
              <label asp-for="Input.Status"></label>
              <select asp-for="Input.Status" class="form-control custom-select" asp-items="Html.GetEnumSelectList<AccountStatus>()">
                <option selected="selected" value="" disabled="disabled"> Select one</option>
              </select>
            </div>
            <div class="form-group">
              <label asp-for="Input.UserRole"></label>
              <select asp-for="Input.UserRole" class="form-control custom-select" asp-items="Html.GetEnumSelectList<UserRoles>()">
                <option selected="selected" value="" disabled="disabled">Select one</option>
              </select>
            </div>
          <!-- /.card-body -->
          <div class="card-footer">
            <button type="submit" class="btn btn-outline-primary">Save Changes</button>
          </div>
          </div>
        </div>
      </form>
      <!-- /.card -->
    </div>
  </div>
</div>

Investor.Web/Pages/Admin/Account/Index.cshtml
@page
@model Investor.Web.Pages.Admin.Account.Index

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Accounts</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">Accounts</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <table class="table table-borderless">
                    <tr>
                        <th>Account Id</th>
                        <th>EMail</th>
                        <th>Created At</th>
                        <th>Last Login At (UTC)</th>
                        <th>Last Modified At (UTC)</th>
                        <th>Actions</th>
                    </tr>
                    @foreach (var account in Model.Accounts) {
                        <tr>
                            <td id="AccountId">
                                <span>@account.ID</span>
                            </td>
                            <td id="EMail">
                                <span>@account.Email</span>
                            </td>
                            <td id="CreatedAt">
                                <span>@account.CreatedAt</span>
                            </td>
                            <td id="LastLoginAt">
                                <span>@account.LastLoginAt</span>
                            </td>
                            <td id="LastModifiedAt">
                                <span>@account.LastModifiedAt</span>
                            </td>
                            <td>
                                <div class="d-flex flex-row flex-wrap">
                                    <a class="btn btn-outline-info m-1" asp-page="Edit" asp-route-id="@account.ID">Edit</a>
                                    <a class="btn btn-outline-danger m-1" href="#">Disable</a>
                                </div>
                            </td>
                        </tr>
                    }
                </table> 
            </div>
        </div>
    </div>
</div>
  
<!-- /.main-content -->

Investor.Web/Pages/Admin/Account/Pending.cshtml
@page
@model Investor.Web.Pages.Admin.Account.Pending

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Pending Accounts</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-page="/Admin/Account/Index">Accounts</a></li>
                    <li class="breadcrumb-item active">Pending</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <table class="table table-borderless">
                    <tr>
                        <th>Account Id</th>
                        <th>Email</th>
                        <th>Created At</th>
                        <th>Actions</th>
                    </tr>
                    @foreach (var account in Model.PendingAccounts) {
                        <tr>
                            <td class="AccountId">
                                <span>@account.ID</span>
                            </td>
                            <td class="EMail">
                                <span>@account.Email</span>
                            </td>
                            <td class="CreatedAt">
                                <span>@account.CreatedAt</span>
                            </td>
                            <td>
                                <div class="d-flex flex-row flex-wrap">
                                    <a class="btn btn-outline-success m-1" asp-page="Pending" asp-page-handler="UpdateStatus" asp-route-id="@account.ID" asp-route-approve="true">Approve</a>
                                    <a class="btn btn-outline-danger m-1" asp-page="Pending" asp-page-handler="UpdateStatus" asp-route-id="@account.ID" asp-route-approve="false">Reject</a>
                                </div>
                            </td>
                        </tr>
                    }
                </table> 
            </div>
        </div>
    </div>
</div>
  
<!-- /.main-content -->

Investor.Web/Pages/Admin/Account/Roles.cshtml
@page
@model Investor.Web.Pages.Admin.Account.Roles

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>